tasks:
  - name: demo
    init: bin/demo prepare
    command: |
      bin/demo start
      gp ports await 8200
      gp ports await 15433
      gp ports await 8080
      gp ports await 3000
      gp ports list
      gp sync-done demo-start

  - name: yugabytedb-shell
    command: |
      gp sync-await demo-start
      bin/demo yugabytedb-shell

  - name: vault-shell
    command: |
      gp sync-await demo-start
      bin/demo vault-shell
      
ports:
  - name: sqlpad
    description: SQLPad - SQL Queries Executor
    port: 3000
    onOpen: ignore
  - name: ysql
    description: YugabyteDB YSQL API
    port: 5433
    onOpen: ignore
  - name: ycql
    description: YugabyteDB YCQL API
    port: 9042
    onOpen: ignore
  - name: yugabyted-master
    description: YugabyteDB Master UI
    port: 7000
    onOpen: ignore
  - name: demo-api
    description: Demo App API
    port: 7070
    onOpen: ignore
  - name: demo-ui
    description: Demo App UI
    port: 8080
    onOpen: ignore
  - name: vault-agent
    description: Vault Agent for Demo App
    port: 8100
    onOpen: ignore
  - name: vault
    description: Vault
    port: 8200
    onOpen: ignore
  - name: yugabyted-tserver
    description: YugabyteDB Tserver UI
    port: 9000
    onOpen: ignore
  - name: yugabyted-ui
    description: YugabyteDB Cluster UI
    port: 15433
    onOpen: ignore

