version: "3.7"
name: vault-transform-demo

services:
  ## Frontend UI
  transform-demo-ui:
    extends:
      file: docker-compose.yml
      service: transform-demo-ui
    build:
      context: ../demo-ui

  ## Backend API
  transform-demo-api:
    extends:
      file: docker-compose.yml
      service: transform-demo-api
    build:
      context: ../demo-api

  vailt-init:
    extends:
      file: docker-compose.yml
      service: vault-init
    build:
      context: vault-init
