version: '3.7'
name: vault-transform-demo
networks:
  vault-demo:
    ipam:
      driver: default
      config:
        - subnet: "10.5.0.0/16"

services:
  vault:
    depends_on:
      yugabytedb-init:
        condition: service_completed_successfully
    image: hashicorp/vault-enterprise:latest
#    image: hashicorp/vault:latest
    restart: always
    volumes:
      - ./vault:/vault/config:rw
      - ./vault/audit_logs:/var/log/vault:rw
      - /vault/data
    ports:
      - "8200:8200/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault
    entrypoint: "vault server -config=/vault/config"
    environment:
      - VAULT_LICENSE=${VAULT_LICENSE}
    networks:
      - vault-demo
    healthcheck:
      test: ["CMD", "nc","-zvw1","vault", "8200"]
      start_period: 3s
      interval: 3s
      timeout: 2s
      retries: 20
  vault-init:
    depends_on:
      vault:
        condition: service_healthy
    build:
      context: ./vault-init
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/vault
    container_name: vault-init
    entrypoint: ./init.sh
    working_dir: /vault/scripts
    environment:
      - VAULT_LICENSE=${VAULT_LICENSE}
      - VAULT_ADDR=http://vault:8200
      - TERM=xterm-256color
      - SKIP_DOCKER_COMPOSE=1
    networks:
      - vault-demo
  yugabytedb:
    image: yogendra/yugabyte:2.18.4.0-b52
    container_name: yugabytedb
    restart: always
    command: bin/yugabyted start --daemon=false
    ports:
      - "5433:5433/tcp"
      - "15433:15433/tcp"
    environment:
      - YSQL_USER=demo
      - YSQL_PASSWORD=passw0rd
      - YSQL_DB=demo
    networks:
      - vault-demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://yugabytedb:15433"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  vault-agent:
    image: hashicorp/vault:latest
    restart: always
    depends_on:
      vault-init:
        condition: service_completed_successfully
    volumes:
      - ./vault-agent/:/vault/config
    ports:
      - "8100:8100/tcp"
    cap_add:
      - IPC_LOCK
    container_name: vault-agent
    entrypoint: "vault agent -config=/vault/config/agent.hcl"
    networks:
      - vault-demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://vault:8100"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  transform-demo-api:
    image: nicklhw/transform-demo-api
    container_name: transform-demo-api
    restart: always
    depends_on: [vault-agent]
    build:
      context: ../demo-api
    ports:
      - "7070:7070"
    environment:
      - SPRING_CLOUD_VAULT_HOST=vault-agent
      - SPRING_DATASOURCE_URL=jdbc:postgresql://yugabytedb:5433/demo
    networks:
      - vault-demo
  transform-demo-ui:
    image: nicklhw/transform-demo-ui
    container_name: transform-demo-ui
    restart: always
    depends_on: [ transform-demo-api ]
    build:
      context: ../demo-ui
    ports:
      - "8080:8080"
    environment:
      - API_ADDRESS=http://transform-demo-api:7070
    networks:
      - vault-demo
  yugabytedb-init:
    image: yogendra/yugabyte:2.18.4.0-b52
    container_name: yugabytedb-init
    restart: on-failure
    environment:
    - YSQL_USER=demo
    - YSQL_PASSWORD=passw0rd
    - YSQL_DB=demo
    volumes:
    - ./yugabytedb/init.sql:/init.sql
    command:
    - bash
    - -c
    - |
      echo -n "Waiting for yugabytedb to be ready"
      export PGPASSWORD=$$YSQL_PASSWORD
      export PGUSER=$$YSQL_USER
      export PGDATABASE=$$YSQL_DB
      export PGHOST=yugabytedb
      export PGPORT=5433

      until postgres/bin/pg_isready -t 1  &> /dev/null; do echo -n '.'; done
      echo " OK"
      bin/ysqlsh -c 'select version(); select * from yb_servers(); select * from inet_server_addr();'
      bin/ysqlsh -a -f /init.sql
    networks:
      - vault-demo
    depends_on:
      yugabytedb:
        condition: service_healthy
  sqlpad:
    # To use Dockerfile at root of this project, use build instead of image
    # build: ../../
    image: sqlpad/sqlpad:6.11.2
    hostname: 'sqlpad'
    container_name: sqlpad
    ports:
      - '3000:3000'
    environment:
      SQLPAD_ADMIN: 'admin'
      SQLPAD_ADMIN_PASSWORD: 'passw0rd'
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
    volumes:
      - ./sqlpad/seed-data:/etc/sqlpad/seed-data
    networks:
      - vault-demo
