name: Build Docker Images

on:
  push:
    branches: [ "main" ]
    # paths: demo-ui/**
  pull_request:
    branches: [ "main" ]

jobs:  
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          ui:
            - 'demo-ui/**'
          api:
            - 'demo-api/**'       
          vault-init:
            - 'docker-compose/vault-init/**'
    outputs:
      ui: ${{ steps.changes.outputs.ui }}
      api: ${{ steps.changes.outputs.api }}
      vault-init: ${{ steps.changes.outputs.vault-init }}
      
  build-ui:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.ui == 'true' }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: demo-ui/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{secrets.DOCKERHUB_REGISTRY}}/yb-vault-demo-transform-demo-ui:latest
  
  build-api:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.api == 'true' }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: demo-api/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{secrets.DOCKERHUB_REGISTRY}}/yb-vault-demo-transform-demo-api:latest
  
  build-vault-init:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.vault-init == 'true' }}
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: docker-compose/vault-init/
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{secrets.DOCKERHUB_REGISTRY}}/vault-init:latest

